name: AWS ECS Task for GitHub Actions
description: Run and await an ECS Task with useful outputs
branding:
  icon: hard-drive
  color: blue
inputs:
  perx_env:
    type: choice
    description: Nominate the environment in which we're deploying
    required: true
    options:
      - dev
      - qa
      - demo
      - staging
      - prod
  perx_region:
    type: choice
    description: Nominate the region in which we're deploying
    required: true
    options:
      - au
      - us
  definition:
    description: Path on local disk at which your .json task definition exists
    required: true
outputs:
  exit-code:
    description: Equal to the ECS task's exit code
runs:
  using: node16
  main: dist/index.js
