name: AWS ECS Task for GitHub Actions
description: Run and await an ECS Task with useful outputs
branding:
  icon: hard-drive
  color: blue
inputs:
  perx_app_name:
    type: choice
    description: In which application context does the task run?
    required: true
    options:
      - perx-api
      - perx-connect
  perx_env:
    type: choice
    description: Nominate the environment (cluster) in which we're running the task
    required: true
    options:
      - dev
      - qa
      - demo
      - staging
      - prod
  perx_region:
    type: choice
    description: Nominate the region in which we're deploying
    required: true
    options:
      - au
      - us
  definition:
    description: Path on local disk at which your .json task definition exists
    required: true
  subnets:
    description: AWS VPC subnets in which the task runs, formatted as a comma delimited string
    required: false
  security_groups:
    description: AWS Security Group's in which the task runs, formatted as a comma delimited string
    required: false
outputs:
  task-definition-arn:
    description: Provides the ARN of the resultant ECS Task Definition
  task-arns:
    description: Provides the ARNs of all ECS tasks which were started as a comma delimited string
  tasks-started-count:
    description: Produces how many ECS tasks were successfully started
  tasks-started-failed-count:
    description: Produces how many ECS tasks failed to start
runs:
  using: node16
  main: dist/index.js
